Create retire-unpublished.md
ACDguide/Governance pull request #26
Opened 2022-04-29 08:03 UTC by hot007

I have not added this file to the toc until it's been reviewed!!! Please add on merge if approved @paolap or @chloemackallah 

I am not happy with the number rendering here where I've done 'custom' things, if you wish to rework the numbered lists I think it'd help?

This commit attempt to address most of Sharon's issues raised in #10

2022-05-01 23:32 UTC, chloemackallah commented on Governance/retire/retire-unpublished.md
> +2. Create zip archives of model configurationsand move to slow access tape storage if they are required to be kept for reproducibility
"configurations and"

2022-05-02 04:28 UTC, hot007 commented on Governance/retire/retire-unpublished.md
> +2. Create zip archives of model configurationsand move to slow access tape storage if they are required to be kept for reproducibility
Fixed, thank you.

2022-05-15 23:48 UTC, paolap requested changes
I only fixed one misspelling. 
My main concern with this is that is looking at a very specific use case
"plethora of data that is associated with published data creation."
and it is looking at this mostly from a model run point of view.
I think it would benefit from being more generalised. We do have a current issue with lots of data, both model and analysis generated, that is re-use by the community. So basically unpublished data which is not versioned but has been used in publications. 
In conclusion, I'm happy for this to be merged as it is, but then we should discuss at the meeting if we want to generalise this example or add another "unpublished" use case to cover what I described above. In first instance it might even encourage publication.

Another action we should add regardless is "documenting the process" if this data isn't published how we document its provenance. It could be included in associated published data documentation, or you might need a metadata record somewhere which refers specifically to this a separate dataset.

2022-05-16 05:16 UTC, merged

2022-05-16 06:41 UTC, hot007 commented
I very much agree - I think it'd be great to generalise or if it's substantially different, add a whole extra example. 
The second use case you describe certainly might be used as a lever to encourage publication for the purposes of reuse!

And yes, we haven't actually captured provenance here, and i wonder if it belongs more in the "creating" section than "publishing" or "retiring", but it maybe should be mentioned throughout??

2022-05-16 22:09 UTC, paolap commented
The provenance I'm thinking of is about documenting the "retirement" step. It is something that should be added to any use case to complete the dataset information, in a way that if someone asks about the data it's easy to query it and let them know what happen to the data and why, and if there's an alternative way to retrieve it, i.e. from deep storage